version: '3.8'

services:
  pdf-translator:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
    environment:
      - FLASK_ENV=production
      - LIBRETRANSLATE_URL=https://libretranslate.com
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/languages"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Run your own LibreTranslate instance
  # libretranslate:
  #   image: libretranslate/libretranslate:latest
  #   ports:
  #     - "5001:5000"
  #   environment:
  #     - LT_DISABLE_WEB_UI=false
  #     - LT_UPDATE_MODELS=true
  #   restart: unless-stopped